export const UPDATE_FACTORY = 'UPDATE_FACTORY';
export const CREATE_FACTORY = 'CREATE_FACTORY';
export const DELETE_FACTORY = 'DELETE_FACTORY';
export const FETCH_FACTORIES = 'FETCH_FACTORIES';
export const FACTORY_LIST = 'FACTORY_LIST';
export const NEW_FACTORY = 'NEW_FACTORY';
export const FACTORY_UPDATED = 'FACTORY_UPDATED';
export const FACTORY_REMOVED = 'FACTORY_REMOVED';
